apiVersion: v1
kind: Service
metadata:
  name: np-svc
  labels:
    app: np-demo
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: np-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: np-demo
  template:
    metadata:
      labels:
        app: np-demo
    spec:
      containers:
      - name: np-pod
        image: nigelpoulton/k8s-deep-dive:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080