apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    env: book
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: test
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: uber-disk  